#ifndef _MUDCOMM_H_


#define MUDCOMM_LOWEST     1
#define MUDCOMM_NORTH      1
#define MUDCOMM_EAST       2
#define MUDCOMM_SOUTH      3
#define MUDCOMM_WEST       4
#define MUDCOMM_UP         5
#define MUDCOMM_DOWN       6
#define MUDCOMM_ENTER      7
#define MUDCOMM_TURN       8
#define MUDCOMM_KISS       9
#define MUDCOMM_GET        10
#define MUDCOMM_DRINK      11
#define MUDCOMM_EAT        12
#define MUDCOMM_WEAR       13
#define MUDCOMM_WIELD      14
#define MUDCOMM_LOOK       15
//#define MUDCOMM_TASTE      16
#define MUDCOMM_SAY        17
#define MUDCOMM_SHOUT      18
#define MUDCOMM_TELL       19
#define MUDCOMM_CLIMB      20
#define MUDCOMM_SWING      21
#define MUDCOMM_BOUNCE     22
#define MUDCOMM_SMILE      23
#define MUDCOMM_DANCE      24
#define MUDCOMM_KILL       25
#define MUDCOMM_CACKLE     26
#define MUDCOMM_LAUGH      27
#define MUDCOMM_GIGGLE     28
#define MUDCOMM_SHAKE      29
#define MUDCOMM_PUKE       30
#define MUDCOMM_GROWL      31
#define MUDCOMM_SCREAM     32
#define MUDCOMM_INSULT     33
#define MUDCOMM_COMFORT    34
#define MUDCOMM_NOD        35
#define MUDCOMM_SIGH       36
#define MUDCOMM_SULK       37
#define MUDCOMM_PART       38
#define MUDCOMM_TWIST      39
//#define MUDCOMM_SING       40
#define MUDCOMM_CHANT      41
#define MUDCOMM_STAND      42
#define MUDCOMM_SIT        43
#define MUDCOMM_REST       44
#define MUDCOMM_SLEEP      45
#define MUDCOMM_WAKE       46
#define MUDCOMM_DUST       47
#define MUDCOMM_HUNT       48
#define MUDCOMM_HUG        49
#define MUDCOMM_SNUGGLE    50
#define MUDCOMM_CUDDLE     51
#define MUDCOMM_NUZZLE     52
#define MUDCOMM_CRY        53
#define MUDCOMM_SHIMMY     54
#define MUDCOMM_SWIM       55
#define MUDCOMM_FORGE      56
//#define MUDCOMM_BASH       57
#define MUDCOMM_SMASH      58
//#define MUDCOMM_SMELL      59
#define MUDCOMM_DROP       60
#define MUDCOMM_GOTO       61
#define MUDCOMM_WEATHER    62
#define MUDCOMM_READ       63
#define MUDCOMM_POUR       64
#define MUDCOMM_GRAB       65
#define MUDCOMM_REMOVE     66
#define MUDCOMM_PUT        67
#define MUDCOMM_SHUTDOW    68
#define MUDCOMM_SAVE       69
#define MUDCOMM_HIT        70
#define MUDCOMM_STRING     71
#define MUDCOMM_GIVE       72
#define MUDCOMM_QUIT       73
#define MUDCOMM_STAT       74
#define MUDCOMM_SETSKILL   75
#define MUDCOMM_TIME       76
#define MUDCOMM_LOAD       77
#define MUDCOMM_PURGE      78
#define MUDCOMM_SHUTDOWN   79
#define MUDCOMM_IDEA       80
#define MUDCOMM_TYPO       81
#define MUDCOMM_BUG        82
#define MUDCOMM_WHISPER    83
#define MUDCOMM_CAST       84
#define MUDCOMM_AT         85
#define MUDCOMM_ASK        86
#define MUDCOMM_ORDER      87
#define MUDCOMM_SIP        88
#define MUDCOMM_TASTE      89
#define MUDCOMM_SNOOP      90
#define MUDCOMM_FOLLOW     91
#define MUDCOMM_RENT       92
#define MUDCOMM_OFFER      93
#define MUDCOMM_POKE       94
#define MUDCOMM_ADVANCE    95
#define MUDCOMM_ACCUSE     96
#define MUDCOMM_GRIN       97
#define MUDCOMM_BOW        98
#define MUDCOMM_OPEN       99
#define MUDCOMM_CLOSE      100
#define MUDCOMM_LOCK       101
#define MUDCOMM_UNLOCK     102
#define MUDCOMM_LEAVE      103
#define MUDCOMM_APPLAUD    104
#define MUDCOMM_BLUSH      105
#define MUDCOMM_BURP       106
#define MUDCOMM_CHUCKLE    107
#define MUDCOMM_CLAP       108
#define MUDCOMM_COUGH      109
#define MUDCOMM_CURTSEY    110
#define MUDCOMM_FART       111
#define MUDCOMM_FLIP       112
#define MUDCOMM_FONDLE     113
#define MUDCOMM_FROWN      114
#define MUDCOMM_GASP       115
#define MUDCOMM_GLARE      116
#define MUDCOMM_GROAN      117
#define MUDCOMM_GROPE      118
#define MUDCOMM_HICCUP     119
#define MUDCOMM_LICK       120
#define MUDCOMM_LOVE       121
#define MUDCOMM_MOAN       122
#define MUDCOMM_NIBBLE     123
#define MUDCOMM_POUT       124
#define MUDCOMM_PURR       125
#define MUDCOMM_RUFFLE     126
#define MUDCOMM_SHIVER     127
#define MUDCOMM_SHRUG      128
#define MUDCOMM_SING       129
#define MUDCOMM_SLAP       130
#define MUDCOMM_SMIRK      131
#define MUDCOMM_SNAP       132
#define MUDCOMM_SNEEZE     133
#define MUDCOMM_SNICKER    134
#define MUDCOMM_SNIFF      135
#define MUDCOMM_SNORE      136
#define MUDCOMM_SPIT       137
#define MUDCOMM_SQUEEZE    138
#define MUDCOMM_STARE      139
#define MUDCOMM_STRUT      140
#define MUDCOMM_THANK      141
#define MUDCOMM_TWIDDLE    142
#define MUDCOMM_WAVE       143
#define MUDCOMM_WHISTLE    144
#define MUDCOMM_WIGGLE     145
#define MUDCOMM_WINK       146
#define MUDCOMM_YAWN       147
#define MUDCOMM_SNOWBALL   148
#define MUDCOMM_WRITE      149
#define MUDCOMM_HOLD       150
#define MUDCOMM_FLEE       151
#define MUDCOMM_SNEAK      152
#define MUDCOMM_HIDE       153
#define MUDCOMM_BACKSTAB   154
#define MUDCOMM_PICK       155
#define MUDCOMM_STEAL      156
#define MUDCOMM_BASH       157
#define MUDCOMM_RESCUE     158
#define MUDCOMM_KICK       159
#define MUDCOMM_FRENCH     160
#define MUDCOMM_COMB       161
#define MUDCOMM_MASSAGE    162
#define MUDCOMM_TICKLE     163
#define MUDCOMM_PRACTICE   164
#define MUDCOMM_PAT        165
#define MUDCOMM_EXAMINE    166
#define MUDCOMM_TAKE       167
#define MUDCOMM_INFO       168
#define MUDCOMM_SPELLS     169
#define MUDCOMM_PRACTISE   170
#define MUDCOMM_CURSE      171
#define MUDCOMM_USE        172
#define MUDCOMM_WHERE      173
#define MUDCOMM_LEVELS     174
#define MUDCOMM_REROLL     175
#define MUDCOMM_PRAY       176
#define MUDCOMM_COLON      177
#define MUDCOMM_BEG        178
#define MUDCOMM_BLEED      179
#define MUDCOMM_CRINGE     180
#define MUDCOMM_DREAM      181
#define MUDCOMM_FUME       182
#define MUDCOMM_GROVEL     183
#define MUDCOMM_HOP        184
#define MUDCOMM_NUDGE      185
#define MUDCOMM_PEER       186
#define MUDCOMM_POINT      187
#define MUDCOMM_PONDER     188
#define MUDCOMM_PUNCH      189
#define MUDCOMM_SNARL      190
#define MUDCOMM_SPANK      191
#define MUDCOMM_STEAM      192
#define MUDCOMM_TACKLE     193
#define MUDCOMM_TAUNT      194
#define MUDCOMM_THINK      195
#define MUDCOMM_WHINE      196
#define MUDCOMM_WORSHIP    197
#define MUDCOMM_YODEL      198
#define MUDCOMM_TOGGLE     199
#define MUDCOMM_WIZLIST    200
#define MUDCOMM_CONSIDER   201
#define MUDCOMM_GROUP      202
#define MUDCOMM_RESTORE    203
#define MUDCOMM_RETURN     204
#define MUDCOMM_SWITCH     205
#define MUDCOMM_QUAFF      206
#define MUDCOMM_RECITE     207
#define MUDCOMM_USERS      208
#define MUDCOMM_POSE       209
#define MUDCOMM_SILENCE    210
#define MUDCOMM_WIZHELP    211
#define MUDCOMM_CREDITS    212
#define MUDCOMM_DISBAND    213
#define MUDCOMM_VIS        214
#define MUDCOMM_PFLAGS     215
#define MUDCOMM_POOFIN     216
#define MUDCOMM_WIZMSG     217
#define MUDCOMM_DISPLAY    218
#define MUDCOMM_ECHOA      219
#define MUDCOMM_DEMOTE     220
#define MUDCOMM_POOFOUT    221
#define MUDCOMM_WIMPY      222
#define MUDCOMM_BALANCE    223
#define MUDCOMM_WIZLOCK    224
#define MUDCOMM_DEPOSIT    225
#define MUDCOMM_WITHDRAW   226
#define MUDCOMM_IGNORE     227
#define MUDCOMM_SETATTR    228
#define MUDCOMM_TITLE      229
#define MUDCOMM_AGGR       230
#define MUDCOMM_GSAY       231
#define MUDCOMM_CONSENT    232
#define MUDCOMM_SETBIT     233
#define MUDCOMM_HITALL     234
#define MUDCOMM_TRAP       235
#define MUDCOMM_MURDER     236
#define MUDCOMM_237        237
#define MUDCOMM_AUCTION    238
#define MUDCOMM_CHANNEL    239
#define MUDCOMM_FILL       240
#define MUDCOMM_GOSSIP     241
#define MUDCOMM_NOKILL     242
#define MUDCOMM_PAGE       243
#define MUDCOMM_MUDCOMMS   244
#define MUDCOMM_ATTRIBUTES 245
#define MUDCOMM_RULES      246
#define MUDCOMM_TRACK      247
#define MUDCOMM_LISTEN     248
#define MUDCOMM_DISARM     249
#define MUDCOMM_PARRY      250
#define MUDCOMM_DELETE     251
#define MUDCOMM_BAN        252
#define MUDCOMM_ALLOW      253
#define MUDCOMM_PASSWORD   254
#define MUDCOMM_DESCRIPTION 255
#define MUDCOMM_BRIBE      256
#define MUDCOMM_BONK       257
#define MUDCOMM_CALM       258
#define MUDCOMM_RUB        259
#define MUDCOMM_CENSOR     260
#define MUDCOMM_CHOKE      261
#define MUDCOMM_DROOL      262
#define MUDCOMM_FLEX       263
//#define MUDCOMM_JUMP       264
#define MUDCOMM_LEAN       265
#define MUDCOMM_MOON       266
#define MUDCOMM_OGLE       267
#define MUDCOMM_PANT       268
#define MUDCOMM_PINCH      269
#define MUDCOMM_PUSH       270
#define MUDCOMM_SCARE      271
#define MUDCOMM_SCOLD      272
#define MUDCOMM_SEDUCE     273
#define MUDCOMM_SHOVE      274
#define MUDCOMM_SHUDDER    275
#define MUDCOMM_SHUSH      276
#define MUDCOMM_SLOBBER    277
#define MUDCOMM_SMELL      278
#define MUDCOMM_SNEER      279
#define MUDCOMM_SPIN       280
#define MUDCOMM_SQUIRM     281
#define MUDCOMM_STOMP      282
#define MUDCOMM_STRANGLE   283
#define MUDCOMM_STRETCH    284
#define MUDCOMM_TAP        285
#define MUDCOMM_TEASE      286
#define MUDCOMM_TIPTOE     287
#define MUDCOMM_TWEAK      288
#define MUDCOMM_TWIRL      289
#define MUDCOMM_UNDRESS    290
#define MUDCOMM_WHIMPER    291
#define MUDCOMM_EXCHANGE   292
#define MUDCOMM_RELEASE    293
#define MUDCOMM_SEARCH     294
#define MUDCOMM_FLY        295
#define MUDCOMM_LEVITATE   296
#define MUDCOMM_SECRET     297
#define MUDCOMM_LOOKUP     298
#define MUDCOMM_REPORT     299
#define MUDCOMM_SPLIT      300
#define MUDCOMM_WORLD      301
#define MUDCOMM_JUNK       302
#define MUDCOMM_PETITION   303
#define MUDCOMM_DO         304
#define MUDCOMM_APOSTROPHE 305
#define MUDCOMM_CARESS     306
#define MUDCOMM_BURY       307
#define MUDCOMM_DONATE     308
#define MUDCOMM_DIG        309
#define MUDCOMM_SCALE      310
#define MUDCOMM_CUT        311
#define MUDCOMM_SLASH      312
#define MUDCOMM_HACK       313
#define MUDCOMM_YELL       314
#define MUDCOMM_RING       315
//#define MUDCOMM_TUG        316
#define MUDCOMM_JUMP       317
#define MUDCOMM_TRACE      318
#define MUDCOMM_WATER      319
#define MUDCOMM_TOUCH      320
#define MUDCOMM_SCRATCH    321
#define MUDCOMM_WINCE      322
#define MUDCOMM_TOSS       323
#define MUDCOMM_FLAME      324
#define MUDCOMM_ARCH       325
#define MUDCOMM_AMAZE      326
#define MUDCOMM_BATHE      327
#define MUDCOMM_EMBRACE    328
#define MUDCOMM_BRB        329
#define MUDCOMM_ACK        330
#define MUDCOMM_CHEER      331
#define MUDCOMM_SNORT      332
#define MUDCOMM_EYEBROW    333
#define MUDCOMM_BANG       334
#define MUDCOMM_PILLOW     335
#define MUDCOMM_NAP        336
#define MUDCOMM_NOSE       337
#define MUDCOMM_RAISE      338
#define MUDCOMM_HAND       339
#define MUDCOMM_PULL       340
#define MUDCOMM_TUG        341
#define MUDCOMM_WET        342
#define MUDCOMM_MOSH       343
#define MUDCOMM_WAIT       344
#define MUDCOMM_HI5        345
#define MUDCOMM_ENVY       346
#define MUDCOMM_FLIRT      347
#define MUDCOMM_BARK       348
#define MUDCOMM_WHAP       349
#define MUDCOMM_ROLL       350
#define MUDCOMM_BLINK      351
#define MUDCOMM_DUH        352
#define MUDCOMM_GAG        353
#define MUDCOMM_GRUMBLE    354
#define MUDCOMM_DROPKICK   355
#define MUDCOMM_WHATEVER   356
#define MUDCOMM_FOOL       357
#define MUDCOMM_NOOGIE     358
#define MUDCOMM_MELT       359
#define MUDCOMM_SMOKE      360
#define MUDCOMM_WHEEZE     361
#define MUDCOMM_BIRD       362
#define MUDCOMM_BOGGLE     363
#define MUDCOMM_HISS       364
#define MUDCOMM_BITE       365
#define MUDCOMM_HIGHEST    365

#define _MUDCOMM_H_
#endif
